#ifndef MEASUREMENT_CONFIG_H
#define MEASUREMENT_CONFIG_H

#include <stdint.h>

#define MEASUREMENT_FFT_SIZE           (4096U)
#define MEASUREMENT_SAMPLE_RATE_HZ     (390625UL)
#define MEASUREMENT_MIN_SPECTRUM_HZ    (900UL)
#define MEASUREMENT_MAX_SPECTRUM_HZ    (110000UL)
#define MEASUREMENT_EDGE_TOLERANCE_MILLIHZ \
    ((2UL * MEASUREMENT_SAMPLE_RATE_HZ * 1000UL) / MEASUREMENT_FFT_SIZE)
#define MEASUREMENT_SPECTRUM_COUNT     (1200U)
#define MEASUREMENT_PEAK_COUNT         (3U)
#define MEASUREMENT_DEFAULT_PHASE_CDEG (9000U)
#define MEASUREMENT_ADC_RATE_HZ        (25000000UL)
#define MEASUREMENT_DELAY_DEPTH        (8192U)
#define MEASUREMENT_FIXED_LATENCY_SAMPLES (10U)

#define MEASUREMENT_FLAG_OTR           (0x0001U)
#define MEASUREMENT_FLAG_DAC_CLIP      (0x0002U)
#define MEASUREMENT_FLAG_PHASE_RANGE   (0x0004U)

typedef struct {
    uint32_t frequencyMilliHz;
    uint16_t magnitude;
    uint16_t bin;
} MeasurementPeak;

#endif
